// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class BlockedUser
{
    public decimal Id { get; set; }

    public decimal BlockerId { get; set; }

    public decimal BlockedId { get; set; }

    public DateTime? BlockedAt { get; set; }

    public string Reason { get; set; }

    public virtual User Blocked { get; set; }

    public virtual User Blocker { get; set; }
}