// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class CloseFriend
{
    public decimal Id { get; set; }

    public decimal OwnerId { get; set; }

    public decimal FriendId { get; set; }

    public DateTime? AddedAt { get; set; }

    public virtual User Friend { get; set; }

    public virtual User Owner { get; set; }
}