// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class Comment
{
    public decimal CommentId { get; set; }

    public decimal PostId { get; set; }

    public decimal UserId { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Post Post { get; set; }

    public virtual User User { get; set; }
}