// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class Follower
{
    public decimal Id { get; set; }

    public decimal FollowerId { get; set; }

    public decimal FollowedId { get; set; }

    public DateTime? FollowedAt { get; set; }

    public string Status { get; set; }

    public virtual User Followed { get; set; }

    public virtual User FollowerNavigation { get; set; }
}