// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class GroupMember
{
    public decimal Id { get; set; }

    public decimal GroupId { get; set; }

    public decimal UserId { get; set; }

    public DateTime? JoinedAt { get; set; }

    public string Role { get; set; }

    public virtual Group Group { get; set; }

    public virtual User User { get; set; }
}