// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class GroupMessage
{
    public decimal MessageId { get; set; }

    public decimal SenderId { get; set; }

    public decimal GroupId { get; set; }

    public string Content { get; set; }

    public decimal? StatusId { get; set; }

    public DateTime? SentAt { get; set; }

    public virtual Group Group { get; set; }

    public virtual User Sender { get; set; }

    public virtual MessageStatus Status { get; set; }
}