// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class Log
{
    public decimal Id { get; set; }

    public decimal? UserId { get; set; }

    public string Activity { get; set; }

    public string Coment { get; set; }

    public virtual User User { get; set; }
}