// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class MessageStatus
{
    public decimal StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<GroupMessage> GroupMessages { get; set; } = new List<GroupMessage>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}