// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLoader.Models;

public partial class Post
{
    public decimal PostId { get; set; }

    public decimal UserId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string PostComment { get; set; }

    public string PostLocation { get; set; }

    public byte[] Photo { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();

    public virtual User User { get; set; }
}